### ISSUE TITLE
atomvm_adc driver can't work with esp-idf 4.x

### ISSUE THREAD

**Issue by biennguyen94** [atomvm/atomvm_adc#3]
I built AtomVM image including ADC on ubuntu 22.04 (Erlang OTP 25, esp-idf 4.4, latest AtomVM, latest atomvm_adc), then I flashed this image to ESP32 successfully, thenI flashed the .avm application to ESP32, after this I see in minicom the error as below:
![image](https://github.com/atomvm/atomvm_adc/assets/29606092/f50a2391-fb37-4bbe-9358-6e6b6fc9d01f)

FYI, I am now using AtomVM 0.5.0 official release and an old atomvm_adc version (around Mar 2022), ubuntu18.04, esp-idf 3.2, Erlang OTP 21, I can see that adc is working well.

**Comment by UncleGrumpy** [comment]
The error you got indicates a bad `db` setting. Can you post the `adc:start/1` command that you used?

**Comment by biennguyen94** [comment]
I used example adc code as following:
![image](https://github.com/atomvm/atomvm_adc/assets/29606092/27d6d62d-aa4f-4ffd-89d2-19d45a48ad09)

**Comment by UncleGrumpy** [comment]
Thank you! You found a bug for us. PR #4 will fix this issue.

**Comment by biennguyen94** [comment]
thank you, @UncleGrumpy, I tested and it works very well with ADC
